import os
import time

print("This tool fixes al the problem released to ruby,gem,bundle,ssl in metasploit")
time.sleep(3)
os.system("pkg update && pkg upgrade -y")
os.system("pkg install git && pkg install python2 && pkg install ruby && pkg install wget")
print("Now your termux to date.")
time.sleep(2)
os.system("wget https://github.com/gushmazuko/metasploit_in_termux/raw/master/metasploit.sh")
os.system("chmod +x metasploit.sh && ./metasploit.sh")
os.system("pkg install curl")
os.system("pkg upgrade ruby")
os.system("gem install bundle && gem install bundler")
os.system("gem install nokogiri -- --use-system-libraries")
os.system("gem install pkg-config -v '~> 1.1'")
os.system("gem install nokogiri")
os.system("pip2 install bundler")
os.system("bundle update nokogiri")
os.system("bundle config build.nokogiri --use-system-libraries")
os.system("bundle install")
os.system("sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb")
os.system("cd metasploit-framework;sed -i '13,15 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb; sed -i '14 {s/^/#/}' /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb;clear;echo 'Done...'")
print("All fixes have been applied thanks for using this tool.")
print("Thankyou")
